name: pytest-coverage-commentator
on:
  pull_request:
    branches: 
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Sync dependencies
        run: |
          pipenv lock
      - name: Install dependencies
        run: |
          pipenv install --deploy --dev
      - name: format
        uses: rickstaa/action-black@v1.3.3
      - name: Run test suite
        run: |
          pipenv run pytest
      - name: Build coverage file
        run: |
          pipenv run pytest --cache-clear --cov=app tests/ > pytest-coverage.txt
      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
